[licenses]
unlicensed = "deny"
copyleft = "deny"
confidence-threshold = 0.925
allow = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "Zlib",
    "BSD-3-Clause"
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = [
    "RUSTSEC-2020-0056",
]
